language: c++
group: stable
os: linux
before_install:
  - sudo apt-get update

script:
  - sudo apt-get install libirrlicht1.8 libirrlicht-dev libirrlicht-doc
  - sudo apt-get install libsfml-dev
  - cmake .
  - make

notifications:
  email: false
